### ISSUE TITLE
(virtualbox) Is failing the verifier

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey/chocolatey-coreteampackages#841] opened 2017-09-15 12:11 UTC
The latest version of virtualbox is currently failing the verifier, had a quick look at the gist and could not see any reason it should fail:
https://gist.github.com/1f9fb17975c2d5e947d9fb99cd3d48f9

Opening this, as I don't have the possibility myself to look into this until earliest next week.

**Comment by majkinetor** [comment] 2017-10-01 12:59
Perhaps exempt ? Clearly package installs.

**Comment by AdmiringWorm** [comment] 2017-10-01 13:17
While the package definitely installs, I can't add an exemption until I know the reason why the automated test environment reports it as a failure.

It could be a bug in the test environment, in choco, or maybe even something completely different.
Until I know, I won't be adding any exemption for it.

**Comment by AdmiringWorm** [comment] 2017-10-18 14:34
I've been up and down now trying to figure out the issue with why the virtualbox package is failing, I'm unable to figure out the reason.

Everything I've tested so far have succeeded without any problems, the only thing left is to figure out if this may be caused by an unknown bug in the verifier.

**Comment by AdmiringWorm** [comment] 2017-10-30 20:41
I just added an exemption for the virtualbox package, we'll need to revisit the problem of the failing verifier at some point in the future.

As such, let us keep this issue open

**Comment by ferventcoder** [comment] 2017-11-06 16:36
This may help?

~~~
2017-11-06 14:21:58,237 16444 [INFO ] - VirtualBox Extension Pack Personal Use and Evaluation License (PUEL)
2017-11-06 14:21:58,242 16444 [INFO ] - 
2017-11-06 14:21:58,242 16444 [INFO ] - License version 10, 20 July 2017
2017-11-06 14:21:58,247 16444 [INFO ] - 
2017-11-06 14:21:58,247 16444 [INFO ] - PLEASE READ THE FOLLOWING ORACLE VM VIRTUALBOX EXTENSION PACK PERSONAL
2017-11-06 14:21:58,252 16444 [INFO ] - USE AND EVALUATION LICENSE CAREFULLY BEFORE DOWNLOADING OR USING THE
2017-11-06 14:21:58,252 16444 [INFO ] - ORACLE SOFTWARE. THESE TERMS AND CONDITIONS CONSTITUTE A LEGAL AGREEMENT
2017-11-06 14:21:58,257 16444 [INFO ] - BETWEEN YOU AND ORACLE.
2017-11-06 14:21:58,257 16444 [INFO ] - 
2017-11-06 14:21:58,262 16444 [INFO ] - ORACLE AMERICA, INC. ("ORACLE") IS WILLING TO LICENSE THE PRODUCT DEFINED
2017-11-06 14:21:58,267 16444 [INFO ] - IN SECTION 1 BELOW ONLY ON THE CONDITION THAT YOU ACCEPT ALL OF THE TERMS
2017-11-06 14:21:58,272 16444 [INFO ] - CONTAINED IN THIS VIRTUALBOX EXTENSION PACK PERSONAL USE AND EVALUATION
2017-11-06 14:21:58,272 16444 [INFO ] - LICENSE AGREEMENT ("AGREEMENT").
2017-11-06 14:21:58,277 16444 [INFO ] - 
2017-11-06 14:21:58,277 16444 [INFO ] - IF YOU ARE AGREEING TO THIS LICENSE ON BEHALF OF AN ENTITY (RATHER THAN
2017-11-06 14:21:58,282 16444 [INFO ] - AS AN INDIVIDUAL HUMAN BEING), YOU REPRESENT THAT YOU HAVE THE APPROPRIATE
2017-11-06 14:21:58,282 16444 [INFO ] - AUTHORITY TO ACCEPT THESE TERMS AND CONDITIONS ON BEHALF OF SUCH ENTITY.
2017-11-06 14:21:58,287 16444 [INFO ] - 
2017-11-06 14:21:58,287 16444 [INFO ] - 1 SUBJECT OF AGREEMENT. This Agreement governs your use of the binary
2017-11-06 14:21:58,292 16444 [INFO ] - software package called "Oracle VM VirtualBox Extension Pack" (the
2017-11-06 14:21:58,292 16444 [INFO ] - "Product"), which contains a set of additional features for "Oracle
2017-11-06 14:21:58,297 16444 [INFO ] - VM VirtualBox" that enhance the operation of multiple virtual machines
2017-11-06 14:21:58,297 16444 [INFO ] - ("Guest Computers") on a single physical computer ("Host Computer"). The
2017-11-06 14:21:58,302 16444 [INFO ] - Product consists of executable files in machine code, script files,
2017-11-06 14:21:58,302 16444 [INFO ] - data files, and all documentation and updates provided to You by Oracle.
2017-11-06 14:21:58,307 16444 [INFO ] - 
2017-11-06 14:21:58,307 16444 [INFO ] - 2 GRANT OF LICENSE. Oracle grants you a personal, non-exclusive,
2017-11-06 14:21:58,312 16444 [INFO ] - non-transferable, limited license without fees to reproduce, install,
2017-11-06 14:21:58,312 16444 [INFO ] - execute, and use internally the Product on Host Computers for
2017-11-06 14:21:58,312 16444 [INFO ] - your Personal Use, Educational Use, or Evaluation. "Personal Use"
2017-11-06 14:21:58,317 16444 [INFO ] - is noncommercial use solely by the person downloading the Product
2017-11-06 14:21:58,317 16444 [INFO ] - from Oracle on a single Host Computer, provided that no more than one
2017-11-06 14:21:58,322 16444 [INFO ] - client or remote computer is connected to that Host Computer and that
2017-11-06 14:21:58,327 16444 [INFO ] - client or remote computer is used solely to remotely view the Guest
2017-11-06 14:21:58,327 16444 [INFO ] - Computer(s). "Educational Use" is any use by teachers or students in
2017-11-06 14:21:58,327 16444 [INFO ] - an academic institution (schools, colleges and universities) as part of
2017-11-06 14:21:58,332 16444 [INFO ] - the institution's educational curriculum. "Evaluation" means testing the
2017-11-06 14:21:58,332 16444 [INFO ] - Product for up to thirty (30) days; after expiry of that term, you are
2017-11-06 14:21:58,337 16444 [INFO ] - no longer permitted to use the Product. Personal Use and/or Educational
2017-11-06 14:21:58,337 16444 [INFO ] - Use expressly exclude any use of the Product for commercial purposes or
2017-11-06 14:21:58,342 16444 [INFO ] - to operate, run, or act on behalf of or for the benefit of a business,
2017-11-06 14:21:58,342 16444 [INFO ] - organization, governmental organization, or educational institution.
2017-11-06 14:21:58,347 16444 [INFO ] - 
2017-11-06 14:21:58,347 16444 [INFO ] - Oracle reserves all rights not expressly granted in this license.
2017-11-06 14:21:58,352 16444 [INFO ] - 
2017-11-06 14:21:58,352 16444 [INFO ] - 3 RESTRICTIONS AND RESERVATION OF RIGHTS.
2017-11-06 14:21:58,357 16444 [INFO ] - 
2017-11-06 14:21:58,357 16444 [INFO ] - (1) The Product and copies thereof provided to you under this Agreement
2017-11-06 14:21:58,362 16444 [INFO ] - are copyrighted and licensed, not sold, to you by Oracle.
2017-11-06 14:21:58,362 16444 [INFO ] - 
2017-11-06 14:21:58,367 16444 [INFO ] - (2) You may not do any of the following: (a) modify any part of the
2017-11-06 14:21:58,367 16444 [INFO ] - Product, except to the extent allowed in the documentation accompanying
2017-11-06 14:21:58,372 16444 [INFO ] - the Product; (b) rent, lease, lend, re-distribute, or encumber the
2017-11-06 14:21:58,377 16444 [INFO ] - Product; (c) remove or alter any proprietary legends or notices contained
2017-11-06 14:21:58,377 16444 [INFO ] - in the Product; or (d) decompile, or reverse engineer the Product
2017-11-06 14:21:58,377 16444 [INFO ] - (except to the extent permitted by applicable law).
2017-11-06 14:21:58,382 16444 [INFO ] - 
2017-11-06 14:21:58,382 16444 [INFO ] - (3) The Product is not designed, licensed or intended for use in the
2017-11-06 14:21:58,382 16444 [INFO ] - design, construction, operation or maintenance of any nuclear facility
2017-11-06 14:21:58,387 16444 [INFO ] - and Oracle and its licensors disclaim any express or implied warranty
2017-11-06 14:21:58,392 16444 [INFO ] - of fitness for such uses.
2017-11-06 14:21:58,392 16444 [INFO ] - 
2017-11-06 14:21:58,392 16444 [INFO ] - (4) No right, title or interest in or to any trademark, service mark, logo
2017-11-06 14:21:58,397 16444 [INFO ] - or trade name of Oracle or its licensors is granted under this Agreement.
2017-11-06 14:21:58,397 16444 [INFO ] - 
2017-11-06 14:21:58,402 16444 [INFO ] - 4 TERMINATION. The Agreement is effective on the date you receive the
2017-11-06 14:21:58,402 16444 [INFO ] - Product and remains effective until terminated. Your rights under this
2017-11-06 14:21:58,407 16444 [INFO ] - Agreement will terminate immediately without notice from Oracle if
2017-11-06 14:21:58,407 16444 [INFO ] - you materially breach it or take any action in derogation of Oracle's
2017-11-06 14:21:58,412 16444 [INFO ] - and/or its licensors' rights to the Product. Oracle may terminate this
2017-11-06 14:21:58,412 16444 [INFO ] - Agreement immediately should any part of the Product become or in Oracle's
2017-11-06 14:21:58,417 16444 [INFO ] - reasonable opinion likely to become the subject of a claim of intellectual
2017-11-06 14:21:58,417 16444 [INFO ] - property infringement or trade secret misappropriation. Upon termination,
2017-11-06 14:21:58,417 16444 [INFO ] - you will cease use of and destroy all copies of the Product under your
2017-11-06 14:21:58,422 16444 [INFO ] - control and confirm compliance in writing to Oracle. Sections 3-9,
2017-11-06 14:21:58,427 16444 [INFO ] - inclusive, will survive termination of the Agreement.
2017-11-06 14:21:58,427 16444 [INFO ] - 
2017-11-06 14:21:58,427 16444 [INFO ] - 5 DISCLAIMER OF WARRANTY. TO THE EXTENT NOT PROHIBITED BY APPLICABLE LAW,
2017-11-06 14:21:58,432 16444 [INFO ] - ORACLE PROVIDES THE PRODUCT "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER
2017-11-06 14:21:58,432 16444 [INFO ] - EXPRESS OR IMPLIED. WITHOUT LIMITING THE FOREGOING, ORACLE SPECIFICALLY
2017-11-06 14:21:58,437 16444 [INFO ] - DISCLAIMS ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
2017-11-06 14:21:58,437 16444 [INFO ] - PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT. The entire risk as
2017-11-06 14:21:58,442 16444 [INFO ] - to the quality and performance of the Product is with you. Should it
2017-11-06 14:21:58,442 16444 [INFO ] - prove defective, you assume the cost of all necessary servicing, repair,
2017-11-06 14:21:58,447 16444 [INFO ] - or correction.
2017-11-06 14:21:58,447 16444 [INFO ] - 
2017-11-06 14:21:58,452 16444 [INFO ] - 6 LIMITATION OF LIABILITY. TO THE EXTENT NOT PROHIBITED BY APPLICABLE LAW,
2017-11-06 14:21:58,452 16444 [INFO ] - IN NO EVENT WILL ORACLE OR ITS LICENSORS BE LIABLE FOR ANY LOST REVENUE,
2017-11-06 14:21:58,457 16444 [INFO ] - PROFIT, DATA, OR DATA USE, OR FOR SPECIAL, INDIRECT, CONSEQUENTIAL,
2017-11-06 14:21:58,462 16444 [INFO ] - INCIDENTAL OR PUNITIVE DAMAGES, HOWEVER CAUSED REGARDLESS OF THE THEORY
2017-11-06 14:21:58,462 16444 [INFO ] - OF LIABILITY, ARISING OUT OF OR RELATED TO THE USE OF OR INABILITY TO
2017-11-06 14:21:58,467 16444 [INFO ] - USE THE PRODUCT, EVEN IF ORACLE HAS BEEN ADVISED OF THE POSSIBILITY OF
2017-11-06 14:21:58,467 16444 [INFO ] - SUCH DAMAGES. In no event will Oracle's liability to you, whether in
2017-11-06 14:21:58,467 16444 [INFO ] - contract, tort (including negligence), or otherwise, exceed the amount
2017-11-06 14:21:58,472 16444 [INFO ] - paid by you for the Product under this Agreement.
2017-11-06 14:21:58,472 16444 [INFO ] - 
2017-11-06 14:21:58,477 16444 [INFO ] - 7 SEPARATELY LICENSED THIRD PARTY TECHNOLOGY. The Product may contain
2017-11-06 14:21:58,477 16444 [INFO ] - or require the use of third party technology that is provided with
2017-11-06 14:21:58,482 16444 [INFO ] - the Product. Oracle may provide certain notices to you in the Product's
2017-11-06 14:21:58,482 16444 [INFO ] - documentation, readmes or notice files in connection with such third party
2017-11-06 14:21:58,487 16444 [INFO ] - technology. Third party technology will be licensed to you either under
2017-11-06 14:21:58,487 16444 [INFO ] - the terms of this Agreement or, if specified in the documentation, readmes
2017-11-06 14:21:58,487 16444 [INFO ] - or notice files, under Separate Terms. Your rights to use Separately
2017-11-06 14:21:58,492 16444 [INFO ] - Licensed Third Party Technology under Separate Terms are not restricted
2017-11-06 14:21:58,492 16444 [INFO ] - in any way by this Agreement. However, for clarity, notwithstanding the
2017-11-06 14:21:58,497 16444 [INFO ] - existence of a notice, third party technology that is not Separately
2017-11-06 14:21:58,497 16444 [INFO ] - Licensed Third Party Technology shall be deemed part of the Product and
2017-11-06 14:21:58,502 16444 [INFO ] - is licensed to You under the terms of this Agreement. "Separate Terms"
2017-11-06 14:21:58,502 16444 [INFO ] - refers to separate license terms that are specified in the Product's
2017-11-06 14:21:58,507 16444 [INFO ] - documentation, readmes or notice files and that apply to Separately
2017-11-06 14:21:58,507 16444 [INFO ] - Licensed Third Party Technology. "Separately Licensed Third Party
2017-11-06 14:21:58,512 16444 [INFO ] - Technology" refers to third party technology that is licensed under
2017-11-06 14:21:58,512 16444 [INFO ] - Separate Terms and not under the terms of this Agreement.
2017-11-06 14:21:58,517 16444 [INFO ] - 
2017-11-06 14:21:58,517 16444 [INFO ] - 8 EXPORT. Export laws and regulations of the United States and any other
2017-11-06 14:21:58,517 16444 [INFO ] - relevant local export laws and regulations apply to the Product. You
2017-11-06 14:21:58,522 16444 [INFO ] - agree that such export laws govern your use of the Product (including
2017-11-06 14:21:58,522 16444 [INFO ] - technical data) provided under this Agreement, and you agree to comply
2017-11-06 14:21:58,527 16444 [INFO ] - with all such export laws and regulations (including "deemed export" and
2017-11-06 14:21:58,527 16444 [INFO ] - "deemed re-export" regulations). You agree that no data, information,
2017-11-06 14:21:58,532 16444 [INFO ] - and/or Product (or direct product thereof) will be exported, directly or
2017-11-06 14:21:58,532 16444 [INFO ] - indirectly, in violation of these laws, or will be used for any purpose
2017-11-06 14:21:58,537 16444 [INFO ] - prohibited by these laws including, without limitation, nuclear, chemical,
2017-11-06 14:21:58,537 16444 [INFO ] - or biological weapons proliferation, or development of missile technology.
2017-11-06 14:21:58,542 16444 [INFO ] - 
2017-11-06 14:21:58,547 16444 [INFO ] - 9 U.S. GOVERNMENT END USERS. Oracle programs, including the Product,
2017-11-06 14:21:58,547 16444 [INFO ] - any operating system, integrated software, any programs installed on
2017-11-06 14:21:58,552 16444 [INFO ] - hardware, and/or documentation, delivered to U.S. Government end users
2017-11-06 14:21:58,557 16444 [INFO ] - are "commercial computer software" pursuant to the applicable Federal
2017-11-06 14:21:58,557 16444 [INFO ] - Acquisition Regulation and agency-specific supplemental regulations. As
2017-11-06 14:21:58,562 16444 [INFO ] - such, use, duplication, disclosure, modification, and adaptation of
2017-11-06 14:21:58,562 16444 [INFO ] - the programs, including any operating system, integrated software,
2017-11-06 14:21:58,567 16444 [INFO ] - any programs installed on the hardware, and/or documentation, shall
2017-11-06 14:21:58,572 16444 [INFO ] - be subject to license terms and license restrictions applicable to the
2017-11-06 14:21:58,572 16444 [INFO ] - programs. No other rights are granted to the U.S. Government.
2017-11-06 14:21:58,577 16444 [INFO ] - 
2017-11-06 14:21:58,577 16444 [INFO ] - 10 MISCELLANEOUS. This Agreement is the entire agreement between you
2017-11-06 14:21:58,582 16444 [INFO ] - and Oracle relating to its subject matter. It supersedes all prior or
2017-11-06 14:21:58,582 16444 [INFO ] - contemporaneous oral or written communications, proposals, representations
2017-11-06 14:21:59,685 16444 [INFO ] - 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
2017-11-06 14:21:59,690 16444 [INFO ] - and warranties and prevails over any conflicting or additional terms
2017-11-06 14:21:59,690 16444 [INFO ] - of any quote, order, acknowledgment, or other communication between
2017-11-06 14:21:59,690 16444 [INFO ] - the parties relating to its subject matter during the term of this
2017-11-06 14:21:59,696 16444 [INFO ] - Agreement. No modification of this Agreement will be binding, unless in
2017-11-06 14:21:59,696 16444 [INFO ] - writing and signed by an authorized representative of each party. If any
2017-11-06 14:21:59,700 16444 [INFO ] - provision of this Agreement is held to be unenforceable, this Agreement
2017-11-06 14:21:59,700 16444 [INFO ] - will remain in effect with the provision omitted, unless omission would
2017-11-06 14:21:59,705 16444 [INFO ] - frustrate the intent of the parties, in which case this Agreement will
2017-11-06 14:21:59,705 16444 [INFO ] - immediately terminate. This Agreement is governed by the laws of the
2017-11-06 14:21:59,705 16444 [INFO ] - State of California, USA, and you and Oracle agree to submit to the
2017-11-06 14:21:59,710 16444 [INFO ] - exclusive jurisdiction of, and venue in, the courts of San Francisco
2017-11-06 14:21:59,710 16444 [INFO ] - or Santa Clara counties in California in any dispute arising out of or
2017-11-06 14:21:59,715 16444 [INFO ] - relating to this Agreement.
2017-11-06 14:21:59,720 16444 [INFO ] - 
2017-11-06 14:21:59,720 16444 [INFO ] - Do you agree to these license terms and conditions (y/n)? 
2017-11-06 14:21:59,725 16444 [INFO ] - License accepted. For batch installaltion add
2017-11-06 14:21:59,725 16444 [INFO ] - --accept-license=b674970f720eb020ad18926a9268607089cc1703908696d24a04aa870f34c8e8
2017-11-06 14:21:59,730 16444 [INFO ] - to the VBoxManage command line.
2017-11-06 14:21:59,730 16444 [INFO ] - 
2017-11-06 14:21:59,735 16444 [INFO ] - Successfully installed "Oracle VM VirtualBox Extension Pack".
~~~

**Comment by majkinetor** [comment] 2018-05-05 10:26
Closing this as I dont see a point and it passed the lifetime.

**Closed by majkinetor** 2018-05-05 10:26 UTC
Labels: Triaging
