### ISSUE TITLE
(libreoffice*) Newest versions stuck waiting for a fix for weeks now.

### ISSUE THREAD

**Issue by martinsstuff** [chocolatey/chocolatey-coreteampackages#1101] opened 2018-08-23 15:36 UTC
## Expected Behavior

Packages should be released and working (duh)

## Current Behavior

Basically what it says in the title. To be exact both are suffering from a "Generic MSI Error" most recent testing files are available here:

Fresh: https://gist.github.com/choco-bot/6f0183c16d72c49edf68ebedf5366ba7

Still: https://gist.github.com/choco-bot/a4a5f30b9a85969f3a242b937dea0938

## Possible Solution

Maintainer "wget" made choco retest the newest fresh package, which resulted in the same error. I don't have any inside knowledge so I am not sure what is being done. I am still opening a bug report here so other people can chime in.

## Steps to Reproduce (for bugs)

[Doesn't apply here]

## Context

I want to get the newest Libre Office version! 😃 

## Your Environment

[At the moment I personally don't have an available testing environment for it]

**Comment by majkinetor** [comment] 2018-08-24 11:06
> [At the moment I personally don't have an available testing environment for it]

There is always testing environment here, just make a branch and enjoy (hat tip to @AdmiringWorm)

**Comment by AdmiringWorm** [comment] 2018-08-24 15:37
> There is always testing environment here

true, but it's still best to also test in the chocolatey testing environment.
After all, alot of stuff is installed on appveyor, that isn't installed in the testing environment. Because of that, some stuff may be missed when only testing on appveyor.

**Comment by majkinetor** [comment] 2018-08-24 17:29
> true, but it's still best to also test in the chocolatey testing environment.
Yeah, but...

The problem is that test environment is anything but easy to install at Vbox + vagrant do have number of issues and basically you need to be a lucky son of a ... to make it work OTB. Even after you fix it, any new `cup` could spoil it. Its like that since beginning of time.

Furthermore, now that docker on windows is here for bunch of programmers installing Vbox is even harder as you need to disable HyperV, restart OS, and pray it works. 

So I think that AV is perfect compared to all this, even with few extra tools that shouldn't be there.

**Comment by AdmiringWorm** [comment] 2018-08-24 17:34
I don't think I've ever had much problems with Vagrant + VirtualBox, although I'll admit that disabling Hyper-V every time I use it is a pain.

> So I think that AV is perfect compared to all this, even with few extra tools that shouldn't be there.

I'm not just talking about the software installed, the images are more or less up to date with windows updates as well, which again would result in missed dependencies, and causing failures when pushed to chocolatey.org.

Bottom line, even if you think it's a pain in the ass, don't skip testing in the chocolatey environment. Consider appveyor tests an addition to the use of the chocolatey environment, not an replacement.

**Comment by majkinetor** [comment] 2018-09-01 15:27
https://github.com/chocolatey/chocolatey-coreteampackages/pull/1103

**Comment by martinsstuff** [comment] 2018-09-02 00:34
@majkinetor Same Generic MSI error according to log.

**Comment by majkinetor** [comment] 2018-09-02 10:06
Yah, it required an update of the OS now that the root cause is found. It will probably be exempted from verifier at this moment.

**Comment by majkinetor** [comment] 2018-09-03 16:44
Closing this as there is nothing more to be done on this side.

**Closed by majkinetor** 2018-09-03 16:44 UTC
Labels: Bug
