### ISSUE TITLE
(python3) upgrade to version 3.5.2 does not work

### ISSUE THREAD

**Issue by CWempe** [chocolatey/chocolatey-coreteampackages#346] opened 2016-10-16 19:49 UTC
Here is the debug-log:

```
PS C:\Users\USERNAME> choco upgrade python3 -debug -y
Chocolatey v0.10.3
Chocolatey is running on Windows v 10.0.14393.0
Command line: "C:\ProgramData\chocolatey\choco.exe" upgrade python3 -debug -y
Received arguments: upgrade python3 -debug -y
The source 'https://chocolatey.org/api/v2/' evaluated to a 'normal' source type
 
NOTE: Hiding sensitive configuration data! Please double and triple
 check to be sure no sensitive data is shown, especially if copying
 output to a gist for review.
Configuration: CommandName='upgrade'|
CacheLocation='C:\Users\USERNAME\AppData\Local\Temp\chocolatey'|
ContainsLegacyPackageInstalls='True'|
CommandExecutionTimeoutSeconds='2700'|WebRequestTimeoutSeconds='30'|
Sources='https://chocolatey.org/api/v2/'|SourceType='normal'|
Debug='True'|Verbose='False'|Force='False'|Noop='False'|
HelpRequested='False'|RegularOutput='True'|QuietOutput='False'|
PromptForConfirmation='False'|AcceptLicense='True'|
AllowUnofficialBuild='False'|Input='python3'|AllVersions='False'|
SkipPackageInstallProvider='False'|PackageNames='python3'|
Prerelease='False'|ForceX86='False'|OverrideArguments='False'|
NotSilent='False'|ApplyPackageParametersToDependencies='False'|
ApplyInstallArgumentsToDependencies='False'|IgnoreDependencies='False'|
AllowMultipleVersions='False'|AllowDowngrade='False'|
ForceDependencies='False'|Information.PlatformType='Windows'|
Information.PlatformVersion='10.0.14393.0'|
Information.PlatformName='Windows'|
Information.ChocolateyVersion='0.10.3.0'|
Information.ChocolateyProductVersion='0.10.3'|
Information.FullName='choco, Version=0.10.3.0, Culture=neutral, PublicKeyToken=79d02ea9cad655eb'|
 
Information.Is64Bit='True'|Information.IsInteractive='True'|
Information.IsUserAdministrator='True'|
Information.IsProcessElevated='True'|
Information.IsLicensedVersion='False'|Information.LicenseType='Foss'|
Features.AutoUninstaller='True'|Features.ChecksumFiles='True'|
Features.AllowEmptyChecksums='False'|
Features.AllowEmptyChecksumsSecure='True'|
Features.FailOnAutoUninstaller='False'|
Features.FailOnStandardError='False'|Features.UsePowerShellHost='True'|
Features.LogEnvironmentValues='False'|Features.VirusCheck='False'|
Features.FailOnInvalidOrMissingLicense='False'|
Features.IgnoreInvalidOptionsSwitches='True'|
Features.UsePackageExitCodes='True'|
Features.UseFipsCompliantChecksums='False'|
Features.ScriptsCheckLastExitCode='False'|
ListCommand.LocalOnly='False'|
ListCommand.IncludeRegistryPrograms='False'|ListCommand.PageSize='25'|
ListCommand.Exact='False'|ListCommand.ByIdOnly='False'|
ListCommand.IdStartsWith='False'|ListCommand.OrderByPopularity='False'|
ListCommand.ApprovedOnly='False'|
ListCommand.DownloadCacheAvailable='False'|
ListCommand.NotBroken='False'|UpgradeCommand.FailOnUnfound='False'|
UpgradeCommand.FailOnNotInstalled='False'|
UpgradeCommand.NotifyOnlyAvailableUpgrades='False'|
NewCommand.AutomaticPackage='False'|
NewCommand.UseOriginalTemplate='False'|SourceCommand.Command='unknown'|
SourceCommand.Priority='0'|FeatureCommand.Command='unknown'|
ConfigCommand.Command='unknown'|PinCommand.Command='unknown'|
_ Chocolatey:ChocolateyUpgradeCommand - Normal Run Mode _
Upgrading the following packages:
python3
By upgrading you accept licenses for the packages.
 
You have python3 v3.5.1.20161002 installed. Version 3.5.2 is available based on your source(s).
Backing up existing python3 prior to operation.
Capturing package files in 'C:\ProgramData\chocolatey\lib\python3'
python3 not upgraded. An error occurred during installation:
 Updating 'python3 3.5.1.20161002' to 'python3 3.5.2' failed. Unable to find a version of 'python' that is compatible with 'python3 3.5.2'.
python3 package files upgrade completed. Performing other installation steps.
The upgrade of python3 was NOT successful.
python3 not upgraded. An error occurred during installation:
 Updating 'python3 3.5.1.20161002' to 'python3 3.5.2' failed. Unable to find a version of 'python' that is compatible with 'python3 3.5.2'.
Attempting rollback
 
Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
 
Failures
 - python3 (exited 1) - python3 not upgraded. An error occurred during installation:
 Updating 'python3 3.5.1.20161002' to 'python3 3.5.2' failed. Unable to find a version of 'python' that is compatible with 'python3 3.5.2'.
Exiting with 1
```

**Comment by gep13** [comment] 2016-10-25 08:22
There is another example of this here:

https://chocolatey.org/packages/notepadplusplus#comment-2967581229

@ferventcoder any thoughts on what is going on here?

**Comment by gep13** [comment] 2016-10-25 08:24
And another message here:

https://chocolatey.org/packages/mongodb.install#comment-2967592319

**Comment by alopezf1987** [comment] 2016-10-25 12:18
Maybe the following upgrade log could also be helpful: [python3.zip](https://github.com/chocolatey/chocolatey-coreteampackages/files/550539/python3.zip)

**Comment by Dmaisano404** [comment] 2016-10-26 02:16
Getting the same error when I did a clean install of python

**Comment by majkinetor** [comment] 2016-10-26 12:41
@Dmaisano404 , try `cinst python3` until we fix the problem.

**Comment by ferventcoder** [comment] 2016-10-26 22:05
@gep13 the notepadplusplus issue and the comment directly below it are why we use exact version dependencies. If I install notepadplusplus 7.0, I expect it to get notepadplusplus.install `7.0` (or perhaps `7.0.0.pkgfixversion`). It's really hard to mess up the exact version dependencies and that is why it is preferred over the version ranges - however it is almost never prudent to use minimum version for the meta/*.install/*.portable packages.

cc @AdmiringWorm @flcdrg @majkinetor

**Comment by ferventcoder** [comment] 2016-10-26 22:07
Here's the issue with MongoDB upgrade - https://chocolatey.org/packages/mongodb (note 3.2.9).

**Comment by ferventcoder** [comment] 2016-10-26 22:10
If we release python with the proper version, this is fixed :+1:

**Comment by AdmiringWorm** [comment] 2016-10-26 22:12
.@ferventcoder if you use exact version `7.1`, wouldn't that prevent installation of dependency with version `7.1.0.pkgfixversion` which I believe is the issue regarding the [notepadplusplus](https://chocolatey.org/packages/notepadplusplus) package?

**Comment by ferventcoder** [comment] 2016-10-26 23:12
@AdmiringWorm the issue regarding notepadplusplus is that someone missed they needed to update both notepladplusplus.install ***and*** notepadplusplus. 

The problem is that you can not just do minimum dependencies when it comes to these kinds of packages. 

So the dependency for notepadplusplus should be either:

* "notepadplusplus v7.1" - `<dependency id="notepadplusplus.install" version="[7.1, 7.2)" />`
* OR "notepadplusplus v7.1.0.pkgfixversion" - `<dependency id="notepadplusplus.install" version=[7.1.0.pkgfixversion]" />`

But never: "notepadplusplus v7.1" - `<dependency id="notepadplusplus.install" version="7.1" />`, because @flcdrg's comment - it will install 7.1 of notepladplusplus, but notepadplusplus.install v8.0 when it comes out - but I wanted 7.1. Also never "notepadplusplus v7.1" - `<dependency id="notepadplusplus.install" />`,

The exact version dependency easily translates to EVERY package in this format no matter what the versioning scheme. The version range is ***very*** subjective based on how the software is versioned, so that same major.minor strategy would not also apply to python:

* "python v3.5.2" - `<dependency id="python3" version="[3.5.2, 3.5.3)" />`
* OR "python v3.5.2.pkgfixversion" - `<dependency id="python3" version=[3.5.2.pkgfixversion]" />`

You can easily start to see why we recommend the exact version dependency. It's not subjective at all, and you get exactly the same version of the meta and the actual, which is what is desired.

**Comment by ferventcoder** [comment] 2016-10-26 23:22
The problem here is not the exact version dependency, it's that some packages were missed getting updated in addition to the other packages.

**Comment by AdmiringWorm** [comment] 2016-10-26 23:34
@ferventcoder 
thank you for clarifying as well giving such a detailed answer, I can see why you guys recommend the exact version. I don't necessarily agree with it though, but that is just because I'm used to something entirely different on the linux distros I'm using.

May I perhaps suggest, adding the recommendation of exact versioning when it comes to meta packages to `Create a chocolatey package` documentation?
I remember trying to find out about what was recommended (and why) or not regarding meta packages,
when I was talking to gep and majkinetor on the au channel yesterday.

**Comment by majkinetor** [comment] 2016-10-27 09:17
> @AdmiringWorm the issue regarding notepadplusplus is that someone missed they needed to update both notepladplusplus.install and notepadplusplus.

No, that is not the issue. There is NO SOMEONE in this case. Package is virtual and all 3 packages should  get updated in the same AU run. However, one of those packages failed. So your system is good until everything works as expected, but fails with any outliers. And this is the reason the system is bad, its not flexibile.

Contrary, if you specify minimum version:

- First time you install something you MAY finish with older version.
- Next time you cup virtual package is irrelevant and dependent pacakge will update.

Also, the problem with this approach is that you need to update ALL dependent packages so you are forcing the other pakcage which doesn't need update to be updated. 

So, virtual package should be changed along with dependent (or vice-versa) but should use minimum version and that will allow that dependent pacakges can use choco fix notation.

**Comment by majkinetor** [comment] 2016-10-27 09:19
So, to recap, the system where you always update the virtual package with minimum version is better as it allows independant fixes on depndant packages and doesn't suffer from any shortcomings mentioned above.

**Comment by ferventcoder** [comment] 2016-10-27 15:53
> So, to recap, the system where you always update the virtual package with minimum version is better as it allows independant fixes on dependent packages and doesn't suffer from any shortcomings mentioned above.

@majkinetor Here's the problem. Let's use python as an example. 

Say there was python and python.install. Say python v2.7.2 took a minimum version dependency on python.install 2.7.2 (`<dependency id="python.install" version="2.7.2" />`. Now imagine that there is also Python v3.5.2 packages available. Now when I as a user call `choco install python --version 2.7.2`, what version of Python will I actually have installed at the end of that?

**Comment by ferventcoder** [comment] 2016-10-27 16:16
> what version of Python will I actually have installed at the end of that?

To answer my own question, you will have Python 3.5.2 installed on the system at the end of that. It doesn't take a rocket scientist to see how that is completely incorrect. I specified 2.7.2 and got 3.5.2. That is easily thousands of times more wrong than forgetting to update the meta/virtual package, which is just a temporary set back and easily correctable, even if it is less flexible.

> the system where you always update the virtual package with minimum version

I'm going to harp on your terminology as it is paramount to the discussion. There are only the two options I specified - ***exact* version** dependency or **version range** dependency. Can we agree that minimum version (e.g. "notepadplusplus v7.1" - `<dependency id="notepadplusplus.install" version="7.1" />`) is completely incorrect?

Unless you've built a system flexible enough to be able to handle `[7.1, 7.2)` (notepad++, but later it may be `[7.1.0, 7.1.1)`, etc (following the older versioning scheme - image below)  and `[3.5.2, 3.5.3)`, there really is no discussion on which option you should use. Until you've shown you completely understand how it works and the implications of all scenarios, it is better to not request that it change either.

It must be flexible enough to deal with changing minds about versioning schemes in the same software as well:
![image](https://cloud.githubusercontent.com/assets/63502/19775105/e8e89652-9c34-11e6-83b8-30480c2cd913.png)

Maybe exact version dependencies are a bit inflexible, but they've worked for 5 years and when the small issues that happen every once in awhile are worked out, they will continue to work for the forseeable future.

The one way you could specify the version range dependency is to always specify 3 segments on the right side (the lower than) side unless all four segments were used, then you are back to exact version range dependencies. Then you also suffer the issue of when the software changes the versioning scheme. If it happens the consequences could be more drastic than exact version dependencies.

The only way I see a change is when we introduce package versions. As in `notepadplusplus.7.1.p1.nupkg` and notepadplusplus.7.1.p2.nupkg (or something like that). This is something we've been talking about and thinking about how to best introduce for nearly five years. Then we won't need package fix version notation, and an exact version dependency would allow for package fixes, which means (you guessed it), the framework automatically allows folks to continue doing what we've been telling them for years with exact version dependencies and it automatically corrects nicely.

**Comment by ferventcoder** [comment] 2016-10-27 16:18
Maybe exact version dependencies are a bit inflexible, but they've worked for 5 years and when the small issues that happen every once in awhile are worked out, they will continue to work for the forseeable future.

The one way you could specify the version range dependency is to always specify 3 segments on the right side (the lower than) side unless all four segments were used, then you are back to exact version range dependencies. Then you also suffer the issue of when the software changes the versioning scheme. If it happens the consequences could be more drastic than exact version dependencies.

The only way I see a change is when we introduce package versions. As in `notepadplusplus.7.1.p1.nupkg`, `notepadplusplus.7.1.p2.nupkg`, etc (or something like that). This is something we've been talking about and thinking about how to best introduce for nearly five years. Then we won't need package fix version notation, and an exact version dependency would allow for package fixes, which means (you guessed it), the framework automatically allows folks to continue doing what we've been telling them for years with exact version dependencies and it automatically corrects nicely.

**Comment by majkinetor** [comment] 2016-10-27 16:58
> The only way I see a change is when we introduce package versions
 
That would be semantically most correct.

> Unless you've built a system flexible enough to be able to handle [7.1, 7.2)

Yeah, I have

```powershell
function global:au_SearchReplace {
  $vmin = [version]$Latest.Version    #7.1.2
  $vmax = [version]::new($vmin.Major, $vmin.Minor+1)   #7.2
  $dep = "[{0},{1})" -f $vmin, $vmax   # [7.1.2, 7.2)
  $dep = "[{0}, {1})" -f $Latest.Version, ([version]$Latest.Version
  @{
        "$($Latest.PackageName).nuspec" = @{
            "(\<dependency .+?`"$($Latest.PackageName).install`" version=)`"([^`"]+)`"" = "`$1`"$dep`""
        }
    }
 }
```

Why wouldn't I use above code as general solution and tweak it for special cases. It would work in the case of python and allow for fixes.

**Comment by ferventcoder** [comment] 2016-10-27 17:00
It's not correct - if 7.1.2 is released, how would you handle it? Please reread ALL that I wrote first.

**Comment by majkinetor** [comment] 2016-10-27 17:03
Above case is for 7.1.2 release. Give examples when it goes wrong pls.

**Comment by majkinetor** [comment] 2016-10-27 17:04
But I could equaly use build part of the [version]. It would still allow for fix.

**Comment by ferventcoder** [comment] 2016-10-27 17:16
The above should not also upgrade to 7.1.3, but it will if that version is released. In other words, what you are suggesting will be incorrect if/when a 7.1.3 release materializes. You still haven't fully grokked what I wrote above. 

> The one way you could specify the version range dependency is to always specify 3 segments on the right side (the lower than) side unless all four segments were used, then you are back to exact version range dependencies.

That is `[7.1.2, 7.1.3.0)`. I change my earlier statement, the right side would be all four version segments, not three.

You must be thinking about all different scenarios and the implications of them. A very thoughtful foresight must be used if you are going to suggest an alternative. Unfortunately I'm still not seeing that you've thought through that. 

I would strongly suggest you stick with exact version dependencies for now.

**Comment by majkinetor** [comment] 2016-10-29 08:37
OK, I pushed an [AU virtual python package](https://github.com/chocolatey/chocolatey-coreteampackages/tree/ad5f74c6a00d19eb4127c45ea852e1a08c87248f/automatic/python). 

Here is the test:
```
master~> $au_NoPlugins = $true; .\update_all.ps1 python* -ForcedPackages 'python python3'
FORCED PACKAGES: python python3
Updating 3 automatic packages at 2016-10-29 10:33:24
Push is disabled
   python is updated to 3.5.2.20161029
   python2 has no updates
   python3 is updated to 3.5.2.20161029
```

So if we do `git commit -m '[AU python python3]' --allow-empty` at this moment  it should fix this problem.

If anybody has complains let me know
@gep13 @AdmiringWorm @ferventcoder

**Comment by gep13** [comment] 2016-10-29 08:43
@majkinetor sounds good to me! 😄

**Comment by majkinetor** [comment] 2016-10-29 08:53
Now, with exact versioning desynchronisation of packages makes them unusable (for either side) which requires effort from maintainers to keep them in sync. Above code for example will probably one day get out of sync as `python3` package may fail even if `python` doesn't (this make happen due to network problems, auto checksum problems etc.)

I was thinking about adding to AU atomic operations on virtual package and its packages:

This is the `python:update.ps1`
```
# . $PSScriptRoot\..\python3\update.ps1   <- I DO THIS NOW

function global:au_SearchReplace {
   @{
        "$($Latest.PackageName).nuspec" = @{
            "(\<dependency .+? version=)`"([^`"]+)`"" = "`$1`"$($Latest.Version)`""
        }
    }
}

update -ChecksumFor none -WithDependency    #  <- SHOULD I DO THIS?
```

So in this ` WithDependency` scenario AU will look into nuspec deps for `python`, take the first one, try to run its updater and then update itself only when dependent package updated successfully. Then AU will push both packages or none if any of them failed. Push could still fail on any of them but this still significantlly reduces the probability of failure as it will happen in almost the same moment of time.

This feature would actually be used almost exclusively for virtual packages.

Now, this is only idea and we should probably talk about it if desync starts to happen with above method that separatelly updates and pushes them.

**Closed by majkinetor** 2016-10-29 08:53 UTC

**Comment by majkinetor** [comment] 2016-10-29 08:56
Pushed

Name	Updated	Pushed	RemoteVersion	NuspecVersion
python	True 🔸	True	3.5.2.20161029	3.5.2
python3	True 🔸	True	3.5.2.20161029	3.5.2
