### ISSUE TITLE
(spotify) -- Hash doesn't Match for SpotifyFullSetup.exe

### ISSUE THREAD

**Issue by 1WindowsPuppetAdmin** [chocolatey/chocolatey-coreteampackages#1252] opened 2019-03-29 09:42 UTC
## Expected Behavior
After downloading the Full Setup executable, it should install/upgrade without erroring.

## Current Behavior
Hashes do not match and the install fails.

## Possible Solution
Update the hash in the chocolateyinstall.ps1

## Steps to Reproduce (for bugs)
1. choco upgrade spotify -y

## Context
Unable to update the package because I am unsure if the installer has been tampered with.

## Your Environment
* Package Version used: 1.1.0.237
* Operating System and version: Windows 10
* Chocolatey version: 0.10.13

**Comment by AdmiringWorm** [comment] 2019-03-29 15:57
Duplicate of #1229

**Closed by AdmiringWorm** 2019-03-29 15:57 UTC
