### ISSUE TITLE
(chocolatey-windowsupdate.extension) KB install throws warnings/errors on php 7.1 install if KB already installed

### ISSUE THREAD

**Issue by photodude** [chocolatey/chocolatey-coreteampackages#623] opened 2017-03-15 12:52 UTC
### Problem description
During the install of PHP 7.1 on Win 7, I get the following notices about warnings/error/failures due to an already installed KB
```ps
Installing KB3035131...
WARNING: Update KB3035131 installation failed with code 0x00240006 (WU_S_ALREADY_INSTALLED: The update to be installed i
s already installed on the system).
WARNING: More details may be found in the installation log (C:\Users\walt\AppData\Local\Temp\chocolatey\KB3035131.Instal
l.evt) or the system CBS log (C:\Windows\Logs\CBS\CBS.log).
ERROR: Update KB3035131 installation failed with code 0x00240006 (WU_S_ALREADY_INSTALLED: The update to be installed is
already installed on the system).
The install of kb3035131 was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\KB3035131\Tools\ChocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 1/2 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - kb3035131 (exited 2359302) - Error while running 'C:\ProgramData\chocolatey\lib\KB3035131\Tools\ChocolateyInstall.ps1'.
 See log for details.
```
### Expected result
The KB install should skip if the KB is already installed.

### Actual result
nonrelevant Warning/Error/failure notices

**Comment by jberezanski** [comment] 2017-03-15 19:17
This is actually an issue with the `chocolatey-windowsupdate.extension`, where the actual installation logic resides.

As I cannot reproduce the problem on my test Win7 machine, I'd like you to provide a few details:
- which updates (KBs) are installed on that system? Please paste the output of the following PowerShell statement:

    `Get-HotFix | Format-Table -AutoSize`

- what is the version of Chocolatey? (`choco --version`)
- if possible, could you provide your Chocolatey log file (C:\ProgramData\Chocolatey\logs\chocolatey.log), for example as as [gist](https://gist.github.com/)?

**Comment by photodude** [comment] 2017-03-16 17:23
- Chocolatey v0.10.3
- Chocolatey log file gist
  - https://gist.github.com/photodude/28629363c6c469274ce694b9c014ea83
- kb gist
  - https://gist.github.com/photodude/0480ba3f074574df245714b9fc7b4a46

**Comment by jberezanski** [comment] 2017-03-16 20:07
Thanks! It looks like one of the updates you have installed has superseded KB3035131. I've been able to reproduce it and a fix is about to be released.

**Comment by jberezanski** [comment] 2017-03-16 20:20
https://chocolatey.org/packages/chocolatey-windowsupdate.extension/1.0.2

**Comment by photodude** [comment] 2017-03-16 20:29
Awesome, thank you.

**Comment by gep13** [comment] 2017-03-17 10:52
@photodude @jberezanski going to go ahead and close this out, as looks like it is resolved.

**Closed by gep13** 2017-03-17 10:52 UTC

**Comment by jberezanski** [comment] 2017-03-17 14:23
I intended to wait for the package to pass moderation and perform the final test, but okay, no need to keep this open, I guess.

**Comment by AdmiringWorm** [comment] 2017-03-17 16:28
@jberezanski package have been approved, I also set it as a trusted package.

**Comment by jberezanski** [comment] 2017-03-17 18:37
Thanks!
