### ISSUE TITLE
fosshub changed - three packages affected

### ISSUE THREAD

**Issue by Redsandro** [chocolatey/chocolatey-coreteampackages#36] opened 2014-12-15 15:46 UTC
I am trying to create the package [`LightAlloy`](https://github.com/Redsandro/chocolatey-coreteampackages/tree/LightAlloy/automatic/lightalloy) but I cannot figure out how to get the download link from fosshub because the functionality changed.

This problem also impacts `Classic-Shell` and `MkvToolNix` on the core repo.

Can anyone figure out how to change this?

This also reminds me of the benefit to have helpers for certain sites, as discussed here: https://github.com/chocolatey/chocolatey/issues/377

If fosshub was a helper, updating the helper would update all affected packages. (Except of course for the ketarin regex/download script.)

**Comment by gep13** [comment] 2015-01-07 07:26
@tomone can we close this issue?

**Comment by Redsandro** [comment] 2015-01-07 12:01
Thanks @TomOne! :+1: 

I would like to apply this to LightAlloy player and pull it into auto updating core team repo. But no time at the moment.

In my opinion, this can stay open until I fixed LightAlloy and pulled it in. Also, I think we need to globalize the function to download from certain sources, so one fix applies to all packages. I think @ferventcoder does not plan to pick this up any time soon, seen as the issue arose in [2013](https://github.com/chocolatey/chocolatey/issues/377), and I'm wondering if we can create helper packages that packages such as the 3 mentioned in this topic can depend upon.

**Comment by gep13** [comment] 2015-01-07 12:19
> In my opinion, this can stay open until I fixed LightAlloy and pulled it in.

Okay dokay.

**Comment by Redsandro** [comment] 2015-01-07 15:16
@TomOne 

Still haven't figured out what's going on with the `DownloadUrlx64` array in your code, but I managed to use the module. Nice! :+1: 

https://github.com/chocolatey/chocolatey-coreteampackages/pull/40

In my package I renamed this to `Get-UrlFromFosshub`. It makes sense to use similar name convention as I used in my previous helper extensions:

* `Get-UrlFromRegex` (which is now in Chocolatey vCurrent)
* `Get-UrlFromCnet` (which I want in Chocolatey vCurrent but @ferventcoder thinks it should be a separate helper)

Anyway, a good way to use something that might get implemented into vCurrent or a helper is like so:

```
if (!(Get-Command Get-UrlFromFosshub -errorAction SilentlyContinue)) {
	Import-Module "$($pwd)\Get-UrlFromFosshub.ps1"
}
$url = Get-UrlFromFosshub $url
```

**Comment by Redsandro** [comment] 2015-03-22 12:25
Fosshub changed again?

See https://github.com/chocolatey/chocolatey-coreteampackages/issues/64

We really should have helpers for this: https://github.com/chocolatey/chocolatey/issues/377

**Comment by TomOne** [comment] 2015-05-02 00:07
> Fosshub changed again?
>
> See https://github.com/chocolatey/chocolatey-coreteampackages/issues/64

No, that was just a package-related issue, see https://github.com/chocolatey/chocolatey-coreteampackages/issues/64#issuecomment-98263893

> We really should have helpers for this: https://github.com/chocolatey/chocolatey/issues/377

Not sure about that. While it would certainly help to have less complicated install-scripts, there could be a significant delay until a new version of Chocolatey gets released that catches up when a change in such a download function is needed.

I think it would be better to keep such download functions in separate modules that can be updated independently of Chocolatey itself.

Thoughts?

**Comment by Redsandro** [comment] 2015-05-02 14:41
Just a thought - what about installable helpers?
`chocolatey` -> `helpers` -> `packages`

**Comment by i-give-up** [comment] 2015-10-11 01:44
Hey guys, it seems like the Fosshub links are not working anymore. I'm getting "(403) Forbidden" error so it's not a scripting problem.

As such, packages that uses Fosshub links

- mkvtoolnix
- audacity
- palemoon (ketarin was updated to *not use* fosshub but the change hasn't taken effect on current package yet)

fail to install.

Also, I see the ketarin for avidemux has been updated to use fosshub but the change hasn't taken effect on the current package yet.

**Comment by Redsandro** [comment] 2015-10-11 13:57
The fosshub download page does this on download click:

```
    $(function () {
        $('.xlink').click(function () {
            var elem = $(this);
            $.ajax({
                type: "GET",
                url: "/updateStats/" + elem.attr('file'),
                success: function (data) {
                    if (data == 'alldone') {
                        window.location.href = elem.attr('data');
                    }
                }
            });
            return false;
        });
    });
```

I.e. this sends a request to:  
`http://www.fosshub.com/updateStats/mkvtoolnix`
and then it changes the location to:  
`http://download.fosshub.com/Protected/expiretime=1444570626;badurl=aHR0cDovL3d3dy5mb3NzaHViLmNvbS9NS1ZUb29sTml4Lmh0bWw=/746380211b8d20f1a005e6ce981ef454857dd0e14a2b2e48673da4b7aebc7ee6/MKVToolNix/mkvtoolnix-64bit-8.4.0-1-setup.exe`

Obviously the last one is generated on pageview, but when I do these steps manually, I still don't get the download.

Maybe the link is only valid for a second. Someone should automate this in powershell.

Also I still recommend adding these packages and let other packages depend on them:

* `choco-helper-fosshub`
* `choco-helper-softonic`

etc.

Fix one package to fix all packages with broken dependencies.

**Comment by i-give-up** [comment] 2015-10-11 14:07
It seems like I occasionally have to pass a captcha test (from Cloudflare) to get to any Fosshub page. I don't know if there's any way to bypass that.

**Comment by TomOne** [comment] 2015-10-11 15:04
The packages which download files on Fosshub work fine for me. [mkvtoolnix](https://chocolatey.org/packages/mkvtoolnix/) just had a package-related issue, because the author removed the 8.4.0 version from Fosshub and added 8.4.0-1 instead. Thus the package returned a 404 error.

> It seems like I occasionally have to pass a captcha test (from Cloudflare) to get to any Fosshub page.

Really? I’ve never encountered a captcha when opening a Fosshub page. Perhaps the issue is related to your IP address.

We really should encourage software authors to not use that this :shit: FossHub service and switch to a more reasonable service like GitHub, which has no ads and doesn’t attempt to hamper automated downloads.

**Comment by ferventcoder** [comment] 2015-10-11 22:04
Did the capcha thing just start? I just implemented CloudFlare on Friday for chocolatey.org

**Comment by i-give-up** [comment] 2015-10-12 03:45
If you haven't seen it before, the captcha from CloudFlare [looks like this](http://i.imgur.com/WyavizO.jpg).

I found [this FAQ dated Jan 2015](https://support.cloudflare.com/hc/en-us/articles/203366080-Why-do-I-see-a-captcha-or-challenge-page-Attention-Required-trying-to-visit-a-site-protected-by-CloudFlare-as-a-site-visitor-) about the captcha, so it definitely has been around for some time.

**Comment by ferventcoder** [comment] 2015-10-12 03:51
Ah okay, it's from FossHub and not from https://chocolatey.org

**Comment by i-give-up** [comment] 2015-10-12 14:16
Okay, the Fosshub-genlink link works fine when I use a U.S. VPN.

No one seems to have raised this issue other than me, so maybe it's not a big deal?

**Comment by TomOne** [comment] 2016-03-27 18:51
This issue doesn’t seems to require any more TODOs. Can it be closed?

**Comment by gep13** [comment] 2016-03-27 19:11
@TomOne I have been leaving this one open, as I have on my todo list to create a Chocolatey Extension package that other packages can take a dependency on, rather than each package including the current extra .ps1 file.

**Comment by wickles** [comment] 2016-03-27 21:56
I noticed the classic-shell package now uses a mediafire link. I opted not to install via chocolatey because of that, although I noticed since then that it is actually an 'official' mirror listed on the project webpage. Would it be possible to switch back to fosshub now? That seems to be their only proper official host.

**Comment by Redsandro** [comment] 2016-03-28 11:59
@wickles fosshub links seem to implement captcha for certain IPs and VPNs. So the downloads cannot be reliably automated.

**Comment by dtgm** [comment] 2016-05-22 14:58
@Redsandro Just to clarify, fosshub uses CloudFlare, so it is CloudFlare implementing this restriction, and not something FossHub has control over AFAIK. Just something to keep in mind for other software distribution sites that may switch over to CloudFlare CDN.

@ferventcoder Because of ^^^, chocolatey packages should also be affected. I've seen CloudFlare captcha quite often when web browsing via Tor. Tor concentrates web traffic to specific IPs which subsequently get flagged as suspicious by CloudFlare. I haven't actually tested installing packages using chocolatey.org through tor though.

@wickles "fosshub [...] their only proper official host" seems to be a bit misleading given both distribution links are third party CDNs. The downside of using FossHub is what @Redsandro mentioned. The downside of mediafire is it could be from a free account and subject to limited bandwidth restrictions. I am not familiar with mediafire, but other cloud file services just cut off access to the account/file for the month if it exceeds an arbitrary bandwidth transfer threshold. So should that occur, that would be worse than FossHub/CloudFlare restriction. At this point MediaFlare wins because of [KISS](https://wikipedia.org/wiki/KISS_principle).

**Comment by ferventcoder** [comment] 2016-05-23 03:15
MediaFire has a bandwidth of a certain amount that rolls over each month (unused amounts). I don't remember all of the details but I have one of those.

CloudFlare has those captchas turned on by default, but you can adjust them. I had to adjust them for dot org.

**Comment by gep13** [comment] 2016-10-06 20:01
Calling this one down as well.

**Closed by gep13** 2016-10-06 20:01 UTC
