### ISSUE TITLE
cyg-get error

### ISSUE THREAD

**Issue by chantisnake** [chocolatey/chocolatey-coreteampackages#226] opened 2016-06-07 15:22 UTC
I try to run cyg-get and it is giving me this error:
```
C:\ProgramData\chocolatey\lib\cyg-get\tools\cyg-get.ps1 : Please ensure you have Cygwin installed.
To install please call 'choco install cygwin' (optionally add -y to autoconfirm).
ERROR: This command cannot be run due to the error: The system cannot find the file specified.
At line:1 char:1
+ & 'C:\ProgramData\chocolatey\lib\cyg-get\tools\cyg-get.ps1'  install  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,cyg-get.ps1
```

I tried reinstall Cygwin， and it still doesn't work

**Comment by chantisnake** [comment] 2016-06-07 15:41
I have noticed the `$cygwinSetup = "C:\cygwin64\cygwinsetup.exe"`

but I cannot find `cygwinsetup.exe` anywhere in my computer...

**Comment by chantisnake** [comment] 2016-06-07 15:50
I copied the install file into Cygwin path and rename it to `cygwinsetup.exe works`

**Comment by danwizard208** [comment] 2016-08-11 04:05
This is a duplicate of #200

**Closed** 2016-08-11 05:25 UTC
