### ISSUE TITLE
chocolatey-uninstall.extension depends on unreleased chocolatey-core.extension v1.0

### ISSUE THREAD

**Issue by WrinklyNinja** [chocolatey/chocolatey-coreteampackages#394] opened 2016-11-13 15:37 UTC
I have a [CI build](https://ci.appveyor.com/project/WrinklyNinja/loot) that uses Chocolatey to install Inno Setup. Its package depends on the [chocolatey-uninstall.extension](https://chocolatey.org/packages/chocolatey-uninstall.extension) package, which was just updated yesterday to depend on the [chocolatey-core.extension](https://chocolatey.org/packages/chocolatey-core.extension) package (weirdly, there aren't any previous versions listed).

However, the new `chocolatey-core.extension` package dependency is at v1.0, and the latest available version is v0.1.3. Most of the `chocolatey-uninstall.extension` page is filled with huge warnings about build failures, so I'm surprised that a) the package was still allowed to be published and break dependent workflows such as mine, and b) nobody else seems to have filed a bug report about it.

**Comment by ferventcoder** [comment] 2016-11-13 15:43
@chocolatey/chocolateycommunitypackages folks - looks like there is a mistake in the latest version. @gep13 let's not unlist the version before deprecation before the new one is approved.

**Comment by ferventcoder** [comment] 2016-11-13 15:45
@WrinklyNinja the new deprecated version of the package has not yet been approved - the issue is the older versions have been unlisted. It looks like folks got a little ahead of themselves.

**Comment by ferventcoder** [comment] 2016-11-13 15:48
I just relisted https://chocolatey.org/packages/chocolatey-uninstall.extension/1.1.0, so everything should work again.

@majkinetor @gep13 @AdmiringWorm something you will need to unlist once the other version gets fixed and approved.

**Comment by WrinklyNinja** [comment] 2016-11-13 15:53
Yep, that seems to have fixed things, thanks for the quick resolution.

**Comment by ferventcoder** [comment] 2016-11-13 15:54
@WrinklyNinja to provide more detail - a package dependency against a version will grab that version, even when it is unlisted (soft-deleted). If it is a versionless dependency, it grabs the latest version. If all versions are unlisted, it gets the latest unlisted dependency, even one in moderation. The current version in moderation is broken and has not been published, so it was not allowed to be published yet. But because the other approved versions were prematurely unlisted, it caused the issue you are seeing.

**Comment by ferventcoder** [comment] 2016-11-13 15:55
Reopening because the one in moderation does need to be fixed.

**Comment by gep13** [comment] 2016-11-13 20:06
@WrinklyNinja apologies for the inconvenience.  This required dependency package has been pushed, and the tests have been set to re-run on the uninstall extension, which should put it through the moderation queue.  Please let me know if you continue to have issues.

I am going to close this issue for now, but feel free to re-open if you still have an issue.

**Closed by gep13** 2016-11-13 20:06 UTC
