### ISSUE TITLE
(firefox) Updating from v59.x to v60.x changed the UI language

### ISSUE THREAD

**Issue by NicoHaase** [chocolatey/chocolatey-coreteampackages#1029] opened 2018-05-11 08:32 UTC
## Expected Behavior
This morning, I've updated Firefox to v60 through Chocolatey. Until yesterday, my browser was configured to use a german UI, which hasn't changed for months through numerous updates. After the update, the UI is english. 

## Steps to Reproduce (for bugs)
1. Install old version of Firefox
2. Check the UI language - I don't know where exactly it is picked up, but ensure to see it in a non-english language
3. Update Firefox to the most recent version

## Your Environment
* Package Version used: Firefox 60.0
* Operating System and version: Windows 10, most recent update version
* Chocolatey version: 0.10.11

**Comment by gep13** [comment] 2018-05-11 14:56
@NicoHaase Would you be able to provide the installation log from when you performed the update?

**Comment by NicoHaase** [comment] 2018-05-11 15:11
Of course, see the attached file

[firefox.log](https://github.com/chocolatey/chocolatey-coreteampackages/files/1995836/firefox.log)

**Comment by AdmiringWorm** [comment] 2018-05-11 16:02
hmm, there hasn't actually been any changes to the package in the last few runs that should cause this issue.

I don't suppose you've needed to use the `l=` in the past.
BTW, you can check which UI language the package will be installing by default by running `Get-Culture` in the powershell prompt (future versions will use `Get-UICulture`)

**Comment by AdmiringWorm** [comment] 2018-05-11 16:03
it's also possible that the uninstall path have changed (We use the uninstall path to detect what the the previous version was installed as)

**Comment by majkinetor** [comment] 2018-05-11 17:16
Perhaps it has something to do with remembered arguments feature ? Did you actually installed previously with `--params` ?

**Comment by NicoHaase** [comment] 2018-05-11 19:54
I don't think I've used any arguments for installing, that was some years ago ;) But on a second computer, the update worked properly (keeping the german localization)

**Comment by cht47** [comment] 2018-05-14 13:11
Can confirm the bug. Provisioned all company PCs with choco install firefox. Today I updated with choco update all and all FF installations changed from german to english.

**Comment by majkinetor** [comment] 2018-05-14 15:44
In log there is no mention of verbose string 'Using locale' or anything from `Get-Locale` function. 
I am not sure how this can happen, but since it looks it didn't, it used default en locale. Either that, or locale can't be parsed any more from uninstaller name:

https://github.com/chocolatey/chocolatey-coreteampackages/blob/5b41c7da5750bdcd54efcfd0ed462cb3cec9616d/automatic/firefox/tools/helpers.ps1#L39-L40

**Comment by AdmiringWorm** [comment] 2018-05-14 15:46
@majkinetor that's because that version of the helper isn't in the firefox package, it was added after this issue was opened and no new version of firefox have been published since (well, except for the firefox-esr package that is).

BTW, I see you removed the triaging label, have you found the cause of this? If not, that label should still be present.

**Comment by majkinetor** [comment] 2018-05-14 15:50
\<rant\>

> Yet another locale problem which  I have every single day on some project. 
It just strengthens the point **of never using non English locale for anything** 
> 
> **NEVER** 🗡 
> Just trust me on this. You can tank me later.

\</rant\>

**Comment by majkinetor** [comment] 2018-05-14 15:52
>BTW, I see you removed the triaging label, have you found the cause of this? If not, that label should still be present.

Yeah, my bad.

**Comment by AdmiringWorm** [comment] 2018-05-14 15:56
I added the bug label again, as I believe it to be one. Just not been able to figure out where yet.

**Comment by majkinetor** [comment] 2018-05-14 15:57
> it was added after this issue was opened and no new version of firefox have been published since

We should probably publish this ASAP, maybe we can get log of another unfortunate person before whole planet updates.

**Comment by majkinetor** [comment] 2018-05-14 16:01
Pattern still works: 

```
master~> 'Mozilla Firefox 60.0 (x64 en-US)' -replace ".+\s([a-zA-Z\-]+)\)",'$1'
en-US
```

**Comment by AdmiringWorm** [comment] 2018-05-14 16:07
@majkinetor That's what I found out as well, which is pretty much why I can't figure out why the language suddenly changed.

**Comment by cht47** [comment] 2018-05-15 07:58
If it helps here is my FF Install log
[install.log](https://github.com/chocolatey/chocolatey-coreteampackages/files/2003884/install.log)
and here the part of the choco log.
[choco.log](https://github.com/chocolatey/chocolatey-coreteampackages/files/2003923/choco.log)

**Comment by NicoHaase** [comment] 2018-05-28 07:20
Any news on this topic? As far as I see, reinstalling does not help either:

C:\WINDOWS\system32>cinst --force firefox --params "l=de-DE"
Chocolatey v0.10.11
Installing the following packages:
firefox
By installing you accept licenses for the packages.
Firefox v60.0.1 already installed. Forcing reinstall of version '60.0.1'.
 Please use upgrade if you meant to upgrade to a new version.
Progress: Downloading Firefox 60.0.1... 100%

Firefox v60.0.1 (forced) [Approved]
firefox package files install completed. Performing other installation steps.
Downloading Firefox 64 bit
  from 'https://download-installer.cdn.mozilla.net/pub/firefox/releases/60.0.1/win64/en-US/Firefox%20Setup%2060.0.1.exe'

...shouldn't the locale parameter documented at the Firefox page force the download of that specific locale version?

**Comment by majkinetor** [comment] 2018-05-28 08:59
>If locale package parameter is not present, this package installs Firefox in the first language which matches this list:

>-    If Firefox is already installed it uses the same language as the already installed one.
>-    The Windows system language.
>-    If Firefox does not support the system language, it will fall back to en-US.

So nah. that wont help. You need to clean registry first I think from quick glance.

I think this locale thing needs redesign. Since this is a monster package which reduces the probability it will be taken by core maintainers, I suggest PR. I personally have almost ZERO motiviation to use (and hence fix) non english stuff.

**Comment by AdmiringWorm** [comment] 2018-05-28 14:46
@majkinetor you can already change the locale by using parameters:
`l=nb-NO` for instance, this should override the registry checks.

If that doesn't work, that would be a bug though, unless firefox doesn't provide the language specified.

**Comment by AdmiringWorm** [comment] 2018-05-28 14:48
@NicoHaase in your case, you actually specified a language that firefox doesn't support (well, they support it but not as `de-DE`, but as `de`).
Always check the following list of supported locales: https://releases.mozilla.org/pub/firefox/releases/latest/README.txt

**Comment by NicoHaase** [comment] 2018-05-28 15:32
Thanks, using the proper locale, I was able to reinstall Firefox with the proper language settings

**Comment by AdmiringWorm** [comment] 2018-05-28 15:45
@NicoHaase just curious.
If you run `Get-Culture` in the powershell windows, what is the output?
I'm guessing it's `de-DE`, and that could be what previous versions of firefox used.
If so, this wouldn't be a bug as I initially though. but rather suggest that we should also test for the 2-letter part of the culture code instead of the full culture.

**Comment by NicoHaase** [comment] 2018-05-28 15:47
Yep, it returns `de-DE`

**Comment by majkinetor** [comment] 2018-05-28 15:48
@AdmiringWorm , then this is documentation bug.

> If Firefox is already installed it uses the same language as the already installed one.

Since @NicoHaase forced it, it was already installed. Hence the en-US is correct.

**Comment by AdmiringWorm** [comment] 2018-05-28 15:51
@majkinetor the documentation also mentioned:
> If locale package parameter is not present, this package installs Firefox in the first language which matches this list:

So the docs is still correct.

Anyways, closing this one and opened #1041 to track the enhancement for checking 2-part culture codes as well.

**Closed by AdmiringWorm** 2018-05-28 15:51 UTC
Labels: Bug, Triaging
