### ISSUE TITLE
(notepadplusplus.install) hits 404 when trying to install

### ISSUE THREAD

**Issue by andmos** [chocolatey/chocolatey-coreteampackages#755] opened 2017-06-09 06:29 UTC
From yesterday `choco install notepadplusplus.install` fails with 404 when trying to install: 

```
Attempt to get headers for https://notepad-plus-plus.org/repository/7.x/7.4.1/npp.7.4.1.Installer.x64.exe failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://notepad-plus-plus.org/reposito
ry/7.x/7.4.1/npp.7.4.1.Installer.x64.exe'. Exception calling "GetResponse" with "0" argument(s): "The remote server retu
rned an error: (404) Not Found."
Downloading notepadplusplus 64 bit
  from 'https://notepad-plus-plus.org/repository/7.x/7.4.1/npp.7.4.1.Installer.x64.exe'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://notepad-plus-plus.org/rep
ository/7.x/7.4.1/npp.7.4.1.Installer.x64.exe'. Exception calling "GetResponse" with "0" argument(s): "The remote server
 returned an error: (404) Not Found."
This package is likely not broken for licensed users - see https://chocolatey.org/docs/features-private-cdn.
The install of notepadplusplus.install was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\notepadplusplus.install\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```

Looks like the version no longe exists?

**Comment by AdmiringWorm** [comment] 2017-06-09 15:12
yes, the notepadplusplus meta package was rolled back yesterday because of the following message posted on their website:
https://notepad-plus-plus.org/news/back-to-v7.3.3.html
> A critical regression (in replace in files feature) has been found in v7.4.1, a new version with fix will come out this weekend. In the meantime please use Notepad++ v7.3.3. Sorry for the inconvenience.

The problem is though, that I completely forgot about the meta package. But I believe @ferventcoder have already taken care of that, so I'm closing this one now.

**Closed by AdmiringWorm** 2017-06-09 15:12 UTC

**Comment by ferventcoder** [comment] 2017-06-09 15:54
Non-meta package 👍

**Comment by AdmiringWorm** [comment] 2017-06-09 15:54
Ops, that's what I get for having my focus elsewhere when typing. Fixed...

**Comment by andmos** [comment] 2017-06-10 17:13
👍👍

**Comment by AdmiringWorm** [comment] 2017-06-11 04:04
@andmos 
I take it that you're satisfied with the recent fix, anyways: If there is any questions (either a problem with a package, or a suggestion on how to improve it, then don't hesitate to ask, as long as it is hosted in this repository of course).
