### ISSUE TITLE
(gimp) Fails to upgrade/install on Windows 7 32-bit

### ISSUE THREAD

**Issue by nerdyCamel** [chocolatey/chocolatey-coreteampackages#1028] opened 2018-05-09 14:41 UTC
## Expected Behavior
Version 2.10.0 should be installable. 

## Current Behavior

When trying to upgrade from version 2.8.22.20171021 or trying a fresh install of version 2.10.0, the installation fails with the following message. 

> ERROR: Running ["C:\ProgramData\chocolatey\lib\gimp\tools\gimp-2.10.0-**x64**-setup.exe" /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP- /LOG="C:\cygwin\tmp\chocolatey\gimp.2.10.0.InnoSetup.log" ] was not successful. Exit code was '1'.

## Steps to Reproduce (for bugs)
run 'choco install gimp' (or 'choco upgrade gimp' if already installed)

## Your Environment

* Package Version used: 2.10.0
* Operating System and version: Windows 7 32-bit
* Chocolatey version: 0.10.11
* Install/uninstall gist:

**Comment by majkinetor** [comment] 2018-05-10 15:08
Confirmed.

It looks like gimp merged x32 and x64 installers.
The current package embeds only x64 version which doesn't exist any more - VERIFICATION.txt shows this original link: 

> Download the following <https://download.gimp.org/mirror/pub/gimp/v2.10/windows/gimp-2.10.0-x64-setup.exe>

```
legal\LICENSE.txt Show
legal\VERIFICATION.txt Show
tools\chocolateyInstall.ps1 Show
tools\gimp-2.10.0-x64-setup.exe Show
```

**Closed** 2018-05-10 15:27 UTC
Labels: Bug
